[package]
name = "io-village"
version = "0.1.0"
edition = "2021"

[dependencies]
io-game = { path = "../io-game" }
io-encounter = { path = "../io-encounter" }
io-world = { path = "../io-world" }
io-types = { path = "../io-types" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"
