[workspace]
members = ["crates/io-types", "crates/io-world", "crates/io-assets"]
default-members = [".", "crates/io-types", "crates/io-world", "crates/io-assets"]
resolver = "2"

[package]
name = "io"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
io-types = { path = "crates/io-types" }
io-world = { path = "crates/io-world" }
io-assets = { path = "crates/io-assets" }
